import wx
from setup import player
from globals.data_store import config
from globals.mensajes import mensajes_categorias, mensajes_sonidos, eventos_lista
from controller.ajustes_controller import AjustesController
from globals.resources import idiomas_disponibles,langs,codes,monedas,lista_voces
class configuracionDialog(wx.Dialog):
	def __init__(self, parent):
		super().__init__(parent, title=_("Configuración"))
		sizer_5 = wx.BoxSizer(wx.VERTICAL)
		labelConfic = wx.StaticText(self, -1, _("Categorías"))
		sizer_5.Add(labelConfic, 1, wx.EXPAND, 0)
		self.tree_1 = wx.Treebook(self, wx.ID_ANY)
		sizer_5.Add(self.tree_1, 1, wx.EXPAND, 0)
		self.treeItem_1 = wx.Panel(self.tree_1, wx.ID_ANY)
		self.tree_1.AddPage(self.treeItem_1, _("General"))
		sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
		box_1 = wx.StaticBox(self.treeItem_1, -1, _("Opciones de la app"))
		boxSizer_1 = wx.StaticBoxSizer(box_1,wx.VERTICAL)
		label_language = wx.StaticText(self.treeItem_1, wx.ID_ANY, _("Idioma de VeTube (Requiere reiniciar)"))
		boxSizer_1.Add(label_language)
		self.choice_language = wx.Choice(self.treeItem_1, wx.ID_ANY,choices=langs)
		self.choice_language.SetSelection(codes.index(config['idioma']))
		boxSizer_1.Add(self.choice_language)
		self.check_donaciones = wx.CheckBox(self.treeItem_1, wx.ID_ANY, _("Activar diálogo de donaciones al inicio de la app."))
		self.check_donaciones.SetValue(config['donations'])
		boxSizer_1.Add(self.check_donaciones)
		self.check_salir = wx.CheckBox(self.treeItem_1, wx.ID_ANY, _("preguntar si desea salir de la app al cerrar."))
		self.check_salir.SetValue(config['salir'])
		boxSizer_1.Add(self.check_salir)
		self.check_actualizaciones = wx.CheckBox(self.treeItem_1, wx.ID_ANY, _("Comprobar si hay actualizaciones al iniciar la app"))
		self.check_actualizaciones.SetValue(config['updates'])
		boxSizer_1.Add(self.check_actualizaciones)
		self.check_traduccion = wx.CheckBox(self.treeItem_1, wx.ID_ANY, _("intentar traducir las novedades cuando salga una actualización."))
		self.check_traduccion.SetValue(config['traducir'])
		boxSizer_1.Add(self.check_traduccion)
		label_trans = wx.StaticText(self.treeItem_1, wx.ID_ANY, _("traducción de mensajes: "))
		self.choice_traducir = wx.Choice(self.treeItem_1, wx.ID_ANY, choices=idiomas_disponibles)
		self.choice_traducir.SetSelection(0)
		boxSizer_1.Add(label_trans)
		boxSizer_1.Add(self.choice_traducir)
		label_monedas = wx.StaticText(self.treeItem_1, wx.ID_ANY, _("convertir las donaciones a la divisa: "))
		self.choice_moneditas = wx.Choice(self.treeItem_1, wx.ID_ANY,choices=monedas)
		self.choice_moneditas.SetSelection(0)
		boxSizer_1.Add(label_monedas)
		boxSizer_1.Add(self.choice_moneditas)
		sizer_4.Add(boxSizer_1, 1, wx.EXPAND, 0)
		self.treeItem_2 = wx.Panel(self.tree_1, wx.ID_ANY)
		self.tree_1.AddPage(self.treeItem_2, _("Voz"))
		sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
		box_2 = wx.StaticBox(self.treeItem_2, -1, _("Opciones del habla"))
		boxSizer_2 = wx.StaticBoxSizer(box_2,wx.VERTICAL)
		self.check_1 = wx.CheckBox(self.treeItem_2, wx.ID_ANY, _("Usar voz sapi en lugar de lector de pantalla."))
		self.check_1.SetValue(config['sapi'])
		boxSizer_2.Add(self.check_1)
		label_tts = wx.StaticText(self.treeItem_2, wx.ID_ANY, _("Sistema TTS a usar: "))
		boxSizer_2 .Add(label_tts)
		self.seleccionar_TTS= wx.Choice(self.treeItem_2, wx.ID_ANY, choices=["auto", "piper", "sapi5"])
		self.seleccionar_TTS.SetStringSelection(config['sistemaTTS'])
		if config['sapi']:
			self.seleccionar_TTS.Disable()
		else:
			self.seleccionar_TTS.Enable()
		boxSizer_2 .Add(self.seleccionar_TTS)
		self.chk1 = wx.CheckBox(self.treeItem_2, wx.ID_ANY, _("Activar lectura de mensajes automática"))
		self.chk1.SetValue(config['reader'])
		boxSizer_2.Add(self.chk1)
		label_6 = wx.StaticText(self.treeItem_2, wx.ID_ANY, _("Voz: "))
		boxSizer_2 .Add(label_6)
		self.choice_2 = wx.Choice(self.treeItem_2, wx.ID_ANY,choices=lista_voces)
		self.choice_2.SetSelection(config['voz'])
		boxSizer_2 .Add(self.choice_2)
		self.instala_voces = wx.Button(self.treeItem_2, wx.ID_ANY, label=_("Instalar un paquete de voz..."))
		boxSizer_2.Add(self.instala_voces)
		if config['sistemaTTS'] == "piper":
			self.instala_voces.Disable()
		label_8 = wx.StaticText(self.treeItem_2, wx.ID_ANY, _("Tono: "))
		boxSizer_2 .Add(label_8)
		self.slider_1 = wx.Slider(self.treeItem_2, wx.ID_ANY, config['tono']+10, 0, 20)
		boxSizer_2 .Add(self.slider_1)
		label_9 = wx.StaticText(self.treeItem_2, wx.ID_ANY, _("Volumen: "))
		boxSizer_2 .Add(label_9)
		self.slider_2 = wx.Slider(self.treeItem_2, wx.ID_ANY, config['volume'], 0, 100)
		boxSizer_2 .Add(self.slider_2)
		# desactivar tono/volumen para piper, por ahora no soportados:
		if config['sistemaTTS'] == "piper":
			label_8.Disable()
			self.slider_1.Disable()
			label_9.Disable()
			self.slider_2.Disable()
		label_10 = wx.StaticText(self.treeItem_2, wx.ID_ANY, _("Velocidad: "))
		boxSizer_2 .Add(label_10)
		self.slider_3 = wx.Slider(self.treeItem_2, wx.ID_ANY, config['speed']+10, 0, 20)
		boxSizer_2 .Add(self.slider_3)
		self.boton_prueva = wx.Button(self.treeItem_2, wx.ID_ANY, label=_("&Reproducir prueba."))
		boxSizer_2.Add(self.boton_prueva)
		sizer_6.Add(boxSizer_2, 0, 0, 0)
		self.treeItem_3 = wx.Panel(self.tree_1, wx.ID_ANY)
		self.categoriza=wx.ListCtrl(self.treeItem_3, wx.ID_ANY)
		self.categoriza.EnableCheckBoxes()
		sizer_categoriza = wx.BoxSizer()
		sizer_categoriza.Add(self.categoriza, 1, wx.EXPAND)
		self.treeItem_3.SetSizer(sizer_categoriza)
		self.tree_1.AddPage(self.treeItem_3, _('Categorías'))
		self.treeItem_4 = wx.Panel(self.tree_1, wx.ID_ANY)
		self.check_2 = wx.CheckBox(self.treeItem_4, wx.ID_ANY, _("Activar sonidos"))
		self.check_2.SetValue(config['sonidos'])
		self.soniditos=wx.ListCtrl(self.treeItem_4, wx.ID_ANY)
		self.soniditos.EnableCheckBoxes()
		if config['sonidos']: self.soniditos.Enable()
		else: self.soniditos.Disable()
		sizer_soniditos = wx.BoxSizer()
		sizer_soniditos.Add(self.check_2)
		sizer_soniditos.Add(self.soniditos, 1, wx.EXPAND)
		self.reproducir= wx.Button(self.treeItem_4, wx.ID_ANY, _("&Reproducir"))
		if config['sonidos']: self.reproducir.Enable()
		else: self.reproducir.Disable()
		sizer_soniditos.Add(self.reproducir)
		label_dispositivo = wx.StaticText(self.treeItem_4, wx.ID_ANY, _("Seleccionar dispositivo de audio"))
		self.lista_dispositivos= wx.Choice(self.treeItem_4, wx.ID_ANY,choices=player.devicenames)
		self.lista_dispositivos.SetSelection(config['dispositivo']-1)
		self.establecer_dispositivo = wx.Button(self.treeItem_4, wx.ID_ANY, label=_("&Establecer"))
		self.treeItem_4.SetSizer(sizer_soniditos)
		self.tree_1.AddPage(self.treeItem_4, _('Sonidos'))
		self.treeItem_5 = wx.Panel(self.tree_1, wx.ID_ANY)
		lbl = wx.StaticText(self.treeItem_5, wx.ID_ANY, _("procesados: "))
		self.eventos=wx.ListCtrl(self.treeItem_5, wx.ID_ANY)
		self.eventos.EnableCheckBoxes()
		lbl_1 = wx.StaticText(self.treeItem_5, wx.ID_ANY, _("leídos"))
		self.unread=wx.ListCtrl(self.treeItem_5, wx.ID_ANY)
		self.unread.EnableCheckBoxes()
		sizer_eventos = wx.BoxSizer()
		sizer_eventos.Add(self.eventos, 1, wx.EXPAND)
		sizer_eventos.Add(lbl, 1, wx.EXPAND)
		sizer_eventos.Add(self.unread, 1, wx.EXPAND)
		sizer_eventos.Add(lbl_1, 1, wx.EXPAND)
		self.treeItem_5.SetSizer(sizer_eventos)
		self.tree_1.AddPage(self.treeItem_5, _('Eventos'))
		button_6 = wx.Button(self, wx.ID_OK, _("&Aceptar"))
		button_6.SetDefault()
		sizer_5.Add(button_6, 0, 0, 0)
		button_cansel = wx.Button(self, wx.ID_CANCEL, _("&Cancelar"))
		sizer_5.Add(button_cansel, 0, 0, 0)
		self.treeItem_1.SetSizer(sizer_4)
		self.treeItem_2.SetSizer(sizer_6)
		self.SetSizer(sizer_5)		
		self.Center()
		
		# Categorías
		for contador in range(len(mensajes_categorias)):
			self.categoriza.InsertItem(contador, mensajes_categorias[contador])
			self.categoriza.CheckItem(contador, check=config['categorias'][contador])
		self.categoriza.Focus(0)
		# Sonidos
		for contador in range(len(mensajes_sonidos)):
			self.soniditos.InsertItem(contador, mensajes_sonidos[contador])
			self.soniditos.CheckItem(contador, check=config['listasonidos'][contador])
		self.soniditos.Focus(0)
		# Eventos
		for contador in range(len(config['eventos'])):
			self.eventos.InsertItem(contador, eventos_lista[contador])
			self.eventos.CheckItem(contador, check=config['eventos'][contador])
		self.eventos.Focus(0)
		# Unread
		for contador in range(len(config['unread'])):
			self.unread.InsertItem(contador, eventos_lista[contador])
			self.unread.CheckItem(contador, check=config['unread'][contador])
		self.unread.Focus(0)

		self.ajustes_controller = AjustesController(self)