import wx
from globals.data_store import config
from globals.resources import lista_voces

class PanelVoz(wx.Panel):
	def __init__(self, parent):
		super().__init__(parent, wx.ID_ANY)
		panel_sizer_2 = wx.BoxSizer(wx.VERTICAL)
		box_2 = wx.StaticBox(self, -1, _("Opciones del habla"))
		boxSizer_2 = wx.StaticBoxSizer(box_2, wx.VERTICAL)
		self.check_1 = wx.CheckBox(self, wx.ID_ANY, _("Usar voz sapi en lugar de lector de pantalla."))
		self.check_1.SetValue(config['sapi'])
		boxSizer_2.Add(self.check_1, 0, wx.ALL, 5)
		label_tts = wx.StaticText(self, wx.ID_ANY, _("Sistema TTS a usar: "))
		boxSizer_2.Add(label_tts, 0, wx.ALL, 5)
		self.seleccionar_TTS = wx.Choice(self, wx.ID_ANY, choices=["auto", "piper", "sapi5", "onecore"])
		self.seleccionar_TTS.SetStringSelection(config['sistemaTTS'])
		boxSizer_2.Add(self.seleccionar_TTS, 0, wx.EXPAND | wx.ALL, 5)
		label_6 = wx.StaticText(self, wx.ID_ANY, _("Voz: "))
		boxSizer_2.Add(label_6, 0, wx.ALL, 5)
		self.choice_2 = wx.Choice(self, wx.ID_ANY, choices=lista_voces)
		self.choice_2.SetSelection(config['voz'])
		boxSizer_2.Add(self.choice_2, 0, wx.EXPAND | wx.ALL, 5)
		self.instala_voces = wx.Button(self, wx.ID_ANY, label=_("Instalar un paquete de voz..."))
		boxSizer_2.Add(self.instala_voces, 0, wx.ALL, 5)
		label_8 = wx.StaticText(self, wx.ID_ANY, _("Tono: "))
		boxSizer_2.Add(label_8, 0, wx.ALL, 5)
		self.slider_1 = wx.Slider(self, wx.ID_ANY, config['tono'] + 10, 0, 20)
		boxSizer_2.Add(self.slider_1, 0, wx.EXPAND | wx.ALL, 5)
		label_9 = wx.StaticText(self, wx.ID_ANY, _("Volumen: "))
		boxSizer_2.Add(label_9, 0, wx.ALL, 5)
		self.slider_2 = wx.Slider(self, wx.ID_ANY, config['volume'], 0, 100)
		boxSizer_2.Add(self.slider_2, 0, wx.EXPAND | wx.ALL, 5)
		label_10 = wx.StaticText(self, wx.ID_ANY, _("Velocidad: "))
		boxSizer_2.Add(label_10, 0, wx.ALL, 5)
		self.slider_3 = wx.Slider(self, wx.ID_ANY, config['speed'] + 10, 0, 20)
		boxSizer_2.Add(self.slider_3, 0, wx.EXPAND | wx.ALL, 5)
		self.boton_prueva = wx.Button(self, wx.ID_ANY, label=_("&Reproducir prueba."))
		boxSizer_2.Add(self.boton_prueva, 0, wx.ALL, 5)
		panel_sizer_2.Add(boxSizer_2, 1, wx.EXPAND | wx.ALL, 5)
		self.SetSizer(panel_sizer_2)
